jobs:
  include:
    - stage: build
      name: "Build"
      script: yarn run build
    - stage: bundle
      name: "Bundle"
      script: yarn run bundle
    - stage: test
      name: "Test"
      before_script: cd iterable
      script: yarn run test